#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProbeMon
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Wireless")]
	public partial class RxInfoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertRxInfo(RxInfo instance);
    partial void UpdateRxInfo(RxInfo instance);
    partial void DeleteRxInfo(RxInfo instance);
    #endregion
		
		public RxInfoDataContext() : 
				base(global::ProbeMon.Properties.Settings.Default.WirelessConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public RxInfoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RxInfoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RxInfoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RxInfoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<RxInfo> RxInfos
		{
			get
			{
				return this.GetTable<RxInfo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RxInfo")]
	public partial class RxInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _EntryId;
		
		private System.Data.Linq.Binary _SourceAddr;
		
		private System.Data.Linq.Binary _DestinationAddr;
		
		private System.Data.Linq.Binary _BSSID;
		
		private System.Nullable<byte> _RadioTapAntNoiseDB;
		
		private System.Nullable<byte> _RadioTapAntSignalDB;
		
		private System.Nullable<byte> _RadioTapAntNoiseDBM;
		
		private System.Nullable<byte> _RadioTapRSSI;
		
		private System.Nullable<byte> _RadioTapTxPowerDBM;
		
		private System.Nullable<byte> _RadioTapAntenna;
		
		private System.Nullable<int> _RadioTapChannel;
		
		private string _ProbeRequestSSID;
		
		private System.Nullable<byte> _FrameType;
		
		private System.Nullable<System.DateTime> _TimeStamp;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEntryIdChanging(int value);
    partial void OnEntryIdChanged();
    partial void OnSourceAddrChanging(System.Data.Linq.Binary value);
    partial void OnSourceAddrChanged();
    partial void OnDestinationAddrChanging(System.Data.Linq.Binary value);
    partial void OnDestinationAddrChanged();
    partial void OnBSSIDChanging(System.Data.Linq.Binary value);
    partial void OnBSSIDChanged();
    partial void OnRadioTapAntNoiseDBChanging(System.Nullable<byte> value);
    partial void OnRadioTapAntNoiseDBChanged();
    partial void OnRadioTapAntSignalDBChanging(System.Nullable<byte> value);
    partial void OnRadioTapAntSignalDBChanged();
    partial void OnRadioTapAntNoiseDBMChanging(System.Nullable<byte> value);
    partial void OnRadioTapAntNoiseDBMChanged();
    partial void OnRadioTapRSSIChanging(System.Nullable<byte> value);
    partial void OnRadioTapRSSIChanged();
    partial void OnRadioTapTxPowerDBMChanging(System.Nullable<byte> value);
    partial void OnRadioTapTxPowerDBMChanged();
    partial void OnRadioTapAntennaChanging(System.Nullable<byte> value);
    partial void OnRadioTapAntennaChanged();
    partial void OnRadioTapChannelChanging(System.Nullable<int> value);
    partial void OnRadioTapChannelChanged();
    partial void OnProbeRequestSSIDChanging(string value);
    partial void OnProbeRequestSSIDChanged();
    partial void OnFrameTypeChanging(System.Nullable<byte> value);
    partial void OnFrameTypeChanged();
    partial void OnTimeStampChanging(System.Nullable<System.DateTime> value);
    partial void OnTimeStampChanged();
    #endregion
		
		public RxInfo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntryId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int EntryId
		{
			get
			{
				return this._EntryId;
			}
			set
			{
				if ((this._EntryId != value))
				{
					this.OnEntryIdChanging(value);
					this.SendPropertyChanging();
					this._EntryId = value;
					this.SendPropertyChanged("EntryId");
					this.OnEntryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SourceAddr", DbType="Binary(6) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary SourceAddr
		{
			get
			{
				return this._SourceAddr;
			}
			set
			{
				if ((this._SourceAddr != value))
				{
					this.OnSourceAddrChanging(value);
					this.SendPropertyChanging();
					this._SourceAddr = value;
					this.SendPropertyChanged("SourceAddr");
					this.OnSourceAddrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DestinationAddr", DbType="Binary(6)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary DestinationAddr
		{
			get
			{
				return this._DestinationAddr;
			}
			set
			{
				if ((this._DestinationAddr != value))
				{
					this.OnDestinationAddrChanging(value);
					this.SendPropertyChanging();
					this._DestinationAddr = value;
					this.SendPropertyChanged("DestinationAddr");
					this.OnDestinationAddrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BSSID", DbType="Binary(6)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary BSSID
		{
			get
			{
				return this._BSSID;
			}
			set
			{
				if ((this._BSSID != value))
				{
					this.OnBSSIDChanging(value);
					this.SendPropertyChanging();
					this._BSSID = value;
					this.SendPropertyChanged("BSSID");
					this.OnBSSIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RadioTapAntNoiseDB", DbType="TinyInt")]
		public System.Nullable<byte> RadioTapAntNoiseDB
		{
			get
			{
				return this._RadioTapAntNoiseDB;
			}
			set
			{
				if ((this._RadioTapAntNoiseDB != value))
				{
					this.OnRadioTapAntNoiseDBChanging(value);
					this.SendPropertyChanging();
					this._RadioTapAntNoiseDB = value;
					this.SendPropertyChanged("RadioTapAntNoiseDB");
					this.OnRadioTapAntNoiseDBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RadioTapAntSignalDB", DbType="TinyInt")]
		public System.Nullable<byte> RadioTapAntSignalDB
		{
			get
			{
				return this._RadioTapAntSignalDB;
			}
			set
			{
				if ((this._RadioTapAntSignalDB != value))
				{
					this.OnRadioTapAntSignalDBChanging(value);
					this.SendPropertyChanging();
					this._RadioTapAntSignalDB = value;
					this.SendPropertyChanged("RadioTapAntSignalDB");
					this.OnRadioTapAntSignalDBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RadioTapAntNoiseDBM", DbType="TinyInt")]
		public System.Nullable<byte> RadioTapAntNoiseDBM
		{
			get
			{
				return this._RadioTapAntNoiseDBM;
			}
			set
			{
				if ((this._RadioTapAntNoiseDBM != value))
				{
					this.OnRadioTapAntNoiseDBMChanging(value);
					this.SendPropertyChanging();
					this._RadioTapAntNoiseDBM = value;
					this.SendPropertyChanged("RadioTapAntNoiseDBM");
					this.OnRadioTapAntNoiseDBMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RadioTapRSSI", DbType="TinyInt")]
		public System.Nullable<byte> RadioTapRSSI
		{
			get
			{
				return this._RadioTapRSSI;
			}
			set
			{
				if ((this._RadioTapRSSI != value))
				{
					this.OnRadioTapRSSIChanging(value);
					this.SendPropertyChanging();
					this._RadioTapRSSI = value;
					this.SendPropertyChanged("RadioTapRSSI");
					this.OnRadioTapRSSIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RadioTapTxPowerDBM", DbType="TinyInt")]
		public System.Nullable<byte> RadioTapTxPowerDBM
		{
			get
			{
				return this._RadioTapTxPowerDBM;
			}
			set
			{
				if ((this._RadioTapTxPowerDBM != value))
				{
					this.OnRadioTapTxPowerDBMChanging(value);
					this.SendPropertyChanging();
					this._RadioTapTxPowerDBM = value;
					this.SendPropertyChanged("RadioTapTxPowerDBM");
					this.OnRadioTapTxPowerDBMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RadioTapAntenna", DbType="TinyInt")]
		public System.Nullable<byte> RadioTapAntenna
		{
			get
			{
				return this._RadioTapAntenna;
			}
			set
			{
				if ((this._RadioTapAntenna != value))
				{
					this.OnRadioTapAntennaChanging(value);
					this.SendPropertyChanging();
					this._RadioTapAntenna = value;
					this.SendPropertyChanged("RadioTapAntenna");
					this.OnRadioTapAntennaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RadioTapChannel", DbType="Int")]
		public System.Nullable<int> RadioTapChannel
		{
			get
			{
				return this._RadioTapChannel;
			}
			set
			{
				if ((this._RadioTapChannel != value))
				{
					this.OnRadioTapChannelChanging(value);
					this.SendPropertyChanging();
					this._RadioTapChannel = value;
					this.SendPropertyChanged("RadioTapChannel");
					this.OnRadioTapChannelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProbeRequestSSID", DbType="VarChar(50)")]
		public string ProbeRequestSSID
		{
			get
			{
				return this._ProbeRequestSSID;
			}
			set
			{
				if ((this._ProbeRequestSSID != value))
				{
					this.OnProbeRequestSSIDChanging(value);
					this.SendPropertyChanging();
					this._ProbeRequestSSID = value;
					this.SendPropertyChanged("ProbeRequestSSID");
					this.OnProbeRequestSSIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FrameType", DbType="TinyInt")]
		public System.Nullable<byte> FrameType
		{
			get
			{
				return this._FrameType;
			}
			set
			{
				if ((this._FrameType != value))
				{
					this.OnFrameTypeChanging(value);
					this.SendPropertyChanging();
					this._FrameType = value;
					this.SendPropertyChanged("FrameType");
					this.OnFrameTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeStamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> TimeStamp
		{
			get
			{
				return this._TimeStamp;
			}
			set
			{
				if ((this._TimeStamp != value))
				{
					this.OnTimeStampChanging(value);
					this.SendPropertyChanging();
					this._TimeStamp = value;
					this.SendPropertyChanged("TimeStamp");
					this.OnTimeStampChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
